import React, { useState } from 'react';
import { ResumeData } from '../../types/resume';
import { portfolioIntegration } from '../../services/portfolioIntegration';
import { aiIntegration, AiEnhancementResult } from '../../services/aiIntegration';
import { Button } from '../ui/Button';
import { Code2, Sparkles, Globe, Database, Copy, Check, Terminal, X } from 'lucide-react';

interface IntegrationPanelProps {
  resumeData: ResumeData;
  isOpen: boolean;
  onClose: () => void;
}

export const IntegrationPanel: React.FC<IntegrationPanelProps> = ({
  resumeData,
  isOpen,
  onClose
}) => {
  const [activeTab, setActiveTab] = useState<'portfolio' | 'ai' | 'json'>('portfolio');
  const [copied, setCopied] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiResult, setAiResult] = useState<AiEnhancementResult | null>(null);

  if (!isOpen) return null;

  const portfolioPayload = portfolioIntegration.generatePortfolioPayload(resumeData);
  const rawJson = JSON.stringify(resumeData, null, 2);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRunAiDemo = async () => {
    setAiLoading(true);
    const res = await aiIntegration.enhanceResume(resumeData);
    setAiResult(res);
    setAiLoading(false);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-900">
          <div className="flex items-center gap-2">
            <Terminal size={18} className="text-blue-400" />
            <div>
              <h3 className="text-sm font-semibold text-slate-100">Teammate Integration & Payload Console</h3>
              <p className="text-xs text-slate-400">Exposes zero-modification contracts for Portfolio, AI, & Database modules</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800"
            title="Close Console"
          >
            <X size={18} />
          </button>
        </div>

        {/* Console Nav Tabs */}
        <div className="flex border-b border-slate-800 bg-slate-950 px-4 pt-2 gap-2 text-xs">
          <button
            onClick={() => setActiveTab('portfolio')}
            className={`px-3 py-2 font-medium rounded-t-lg flex items-center gap-1.5 ${
              activeTab === 'portfolio' ? 'bg-slate-900 text-blue-400 border-t-2 border-blue-500' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Globe size={14} /> Portfolio Generator Payload
          </button>
          <button
            onClick={() => setActiveTab('ai')}
            className={`px-3 py-2 font-medium rounded-t-lg flex items-center gap-1.5 ${
              activeTab === 'ai' ? 'bg-slate-900 text-purple-400 border-t-2 border-purple-500' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Sparkles size={14} /> AI Enhancer Interface
          </button>
          <button
            onClick={() => setActiveTab('json')}
            className={`px-3 py-2 font-medium rounded-t-lg flex items-center gap-1.5 ${
              activeTab === 'json' ? 'bg-slate-900 text-emerald-400 border-t-2 border-emerald-500' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Database size={14} /> Raw ResumeData JSON
          </button>
        </div>

        {/* Tab Content */}
        <div className="p-4 overflow-y-auto flex-1 bg-slate-950/50 font-mono text-xs">
          {activeTab === 'portfolio' && (
            <div className="space-y-3">
              <div className="flex justify-between items-center text-slate-400 font-sans text-xs">
                <span>Output generated by <code className="text-blue-400">portfolioIntegration.generatePortfolioPayload(data)</code></span>
                <Button size="sm" variant="ghost" onClick={() => handleCopy(JSON.stringify(portfolioPayload, null, 2))}>
                  {copied ? <Check size={14} /> : <Copy size={14} />} {copied ? 'Copied' : 'Copy Payload'}
                </Button>
              </div>
              <pre className="p-4 bg-slate-900 border border-slate-800 rounded-xl text-slate-300 overflow-x-auto">
                {JSON.stringify(portfolioPayload, null, 2)}
              </pre>
            </div>
          )}

          {activeTab === 'ai' && (
            <div className="space-y-4 font-sans text-xs">
              <div className="p-3 bg-purple-950/30 border border-purple-500/30 rounded-xl space-y-2">
                <p className="font-semibold text-purple-300 flex items-center gap-1.5">
                  <Sparkles size={14} /> AI Resume Enhancer Module Integration Test
                </p>
                <p className="text-slate-400 text-xs">
                  Teammates building the AI Enhancer can connect directly to <code className="text-purple-400 font-mono">aiIntegration.enhanceResume(data)</code>.
                </p>
                <Button
                  size="sm"
                  variant="primary"
                  onClick={handleRunAiDemo}
                  disabled={aiLoading}
                  className="bg-purple-600 hover:bg-purple-500 mt-2"
                >
                  {aiLoading ? 'Simulating AI Analysis...' : 'Test AI Enhancer Payload'}
                </Button>
              </div>

              {aiResult && (
                <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-3 font-sans">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-200">ATS Score Analysis:</span>
                    <span className="px-2.5 py-1 bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded-full font-bold">
                      {aiResult.atsScore} / 100
                    </span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-300 block mb-1">AI Generated Summary Enhancement:</span>
                    <p className="text-slate-400 bg-slate-950 p-2.5 rounded border border-slate-800 text-xs">
                      {aiResult.enhancedSummary}
                    </p>
                  </div>
                  <div>
                    <span className="font-bold text-slate-300 block mb-1">Actionable Resume Suggestions:</span>
                    <ul className="list-disc pl-4 text-slate-400 space-y-1">
                      {aiResult.suggestions?.map((s, i) => (
                        <li key={i}>{s}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}
            </div>
          )}

          {activeTab === 'json' && (
            <div className="space-y-3">
              <div className="flex justify-between items-center text-slate-400 font-sans text-xs">
                <span>Single Master Object <code className="text-emerald-400">ResumeData</code></span>
                <Button size="sm" variant="ghost" onClick={() => handleCopy(rawJson)}>
                  {copied ? <Check size={14} /> : <Copy size={14} />} {copied ? 'Copied' : 'Copy JSON'}
                </Button>
              </div>
              <pre className="p-4 bg-slate-900 border border-slate-800 rounded-xl text-emerald-400 overflow-x-auto">
                {rawJson}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
